#### 函数对象与实例对象
将函数作为对象使用时，称之为函数对象    
new函数产生的对象称之为实例对象，简称对象    
```
function Fn (){

}
const fn = new Fn() // fn是实例对象
console.log(Fn.prototype) //Fn是函数对象

```
#### 同步回调与异步回调  
1. 同步回调
   ```
    const arr = [1, 2, 3, 4]
    arr.forEach(item => {
        console.log(item)
    })
    console.log("----")
    //1 2 3 4 ----

   ```   
2. 异步回调
   放到执行队列中执行 等待主线程执行完才会执行
   ```
    setTimeout(() => {
        console.log("setTimeout")
    }, 0)
    console.log("+++++++")
    //+++++++    setTimeout
   ```

#### JS常见的内置错误  
1. 错误类型
+ Error：所有错误的父类型
+ ReferenceError:引用的变量不存在
+ TypeError：数据类型不正确
+ RangeError:数据不再范围内
+ SyntaxError：语法错误
2. 错误处理   
+ 捕获错误：try...catch    
  ```
    try {
        let a = null
        console.log(a.name)
    } catch (error) {
        console.log(error) 
        console.log(error.message)
        console.log(error.stack)
    }
  ```
+ 抛出错误: throw error  
  ```
     // 给定需求：奇数时刻可执行业务   偶数不可
    function doSomething() {
        if (Date.now() % 2 === 1) {
            console.log("yes")
        } else {
            throw new Error('当前时间不能执行业务')
        }
    }
    try {
        doSomething()
    } catch (error) {
        console.log(error)
    }
  ```
3. 错误对象 
+ message属性：错误相关信息
+ stack属性：函数调用栈记录信息


### Promise的理解
Promise是js中异步编程的一种解决方案    
语法上：promise是一个构造函数   
功能上：**promise对象用来封装一个异步操作并可以获取其结果**
##### 两个特点 
1. 对象的状态不收外界的影响   
   + pending: 初始状态
   + fulfilled: 操作成功
   + rejected: 操作失败
2. 一旦状态改变，就不会再变，任何时候都可以得到这个结果 
   + 从 Pending 变为 Resolved 
   + 从 Pending 变为 Rejected  
  说明:状态的改变只有这2种，且一个promise对象只能改变一次，无论变为成功还是失败，都会有一个结果数据。    
  成功的结果数据一般称为vlaue，失败的结果数据一般称为reason
